### ISSUE TITLE
April Update

### ISSUE THREAD

**Issue by koodeau** [utilly/utilly.github.io#2]
- Google Analytics connected
- All links replaced with more secure links which opens in new tab
- Managed files and links to directories
- Fixed some known bugs
- Now it is more powerful and etc.

See all changes in [this commit](https://github.com/utilly/utilly.github.io/commit/36f8038ced9b8a4d5d86edc3ebb833296cc7555a).

**Comment by kulout** [comment]
I do not see connected PR to this issue. Reopen?
